sudo: false
language: generic

# whitelist
branches:
  only:
    - red2l
    - tarcer

script:
  - curl -OL https://github.com/vermaseren/form/releases/download/v4.2.0/form-4.2.0-x86_64-linux.tar.gz
  - tar -zxf form-4.2.0-x86_64-linux.tar.gz
  - ./form-4.2.0-x86_64-linux/form tests.frm

notifications:
  email: false
